import '@/app/globals.css';
import { ReactNode } from 'react';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Ibovs",
  description: "Generated by Ibrahim Dabwan Naji Ahmed",
  icons: {
    icon: [
      { url: "/favicons/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      { url: "/favicons/favicon.svg", type: "image/svg+xml" },
      { url: "/favicons/favicon.ico" }, // shortcut icon
    ],
    apple: [{ url: "/favicons/apple-touch-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    title: "Ibovs",
  },
  manifest: "/favicons/site.webmanifest",
};
import { cn } from '@/shadcn/utils';
import { fonts } from '@cmpnt/styles';
import { ThemeProvider } from '@/comp/provider/theme-provider';
import { DirectionProvider } from '@/components/ui/direction';
export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html
			lang='ar' dir="rtl"
			suppressHydrationWarning
			className={cn('antialiased ', fonts.fontMono.variable, 'font-sans', fonts.fontSans.variable," ")}
		>
			<body className={cn(fonts.amiri.variable)}>
			<div id="t" > </div>
				<ThemeProvider>
					<DirectionProvider dir='rtl'>{children}</DirectionProvider>
				</ThemeProvider>
			<div id="e" /> 
			</body>
		</html>
	);
}
